### ISSUE TITLE
querying best30 failed with code -11

### ISSUE THREAD

**Issue by iyume** [TheSnowfield/BotArcAPI#14]
## Environment
- Debian 10
- node v15.5.1 (nvm)
- tsc v4.1.3

## Descryption
I successfully setup the project, and have inserted a userbot record into `savedata/arcaccount.db`.

Then when I try to GET `http://myhost/v2/userbest30?usercode=463425308`, I failed.

Here is the key track
```
[2021-01-10 01:06:59] I source/__loader__.ts    Accept Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0 request => GET /v2/use
rbest30 {"usercode":"463425308"}
[2021-01-10 01:06:59] V corefunc/arcfetch.ts    Arcfetch => https://arcapi.lowiro.com/latte/13/auth/login
[2021-01-10 01:07:06] V corefunc/arcfetch.ts    Arcfetch => https://arcapi.lowiro.com/latte/13/user/me
[2021-01-10 01:07:07] V database.arcaccount.update.ts   UPDATE `accounts` SET passwd = ?, device = ?, uid = ?, ucode = ?, token = ?, banned = ? WHERE `name`
 == ?
[2021-01-10 01:07:07] I account/alloc.ts        Allocated account => iyumebot1 9dLYP3rn4eg9JrhSZmkmkreoKT0o/Xyhtzz9afuwMtM=
[2021-01-10 01:07:07] V corefunc/arcfetch.ts    Arcfetch => https://arcapi.lowiro.com/latte/13/user/me
[2021-01-10 01:07:10] V corefunc/arcfetch.ts    Arcfetch => https://arcapi.lowiro.com/latte/13/friend/me/delete
[2021-01-10 01:07:14] V corefunc/arcfetch.ts    Arcfetch => https://arcapi.lowiro.com/latte/13/friend/me/add
[2021-01-10 01:07:21] V database.arcbest30.byuid.ts     SELECT * FROM `cache` WHERE `uid` == ?
[2021-01-10 01:07:21] V database.arcsong.allcharts.ts   SELECT * FROM `charts` ORDER BY `rating` DESC
[2021-01-10 01:07:21] E v2/userbest30.ts                TypeError: Cannot read property 'sid' of undefined
    at /root/service/BotArcAPI/build/source/publicapi/v2/userbest30.js:132:73
    at Generator.next (<anonymous>)
    at fulfilled (/root/service/BotArcAPI/build/source/publicapi/v2/userbest30.js:5:58)
[2021-01-10 01:07:21] I account/recycle.ts      Recycled account => iyumebot1 9dLYP3rn4eg9JrhSZmkmkreoKT0o/Xyhtzz9afuwMtM=
[2021-01-10 01:07:21] V source/__loader__.ts    Send response back
```

## Others
I am able to GET `http://myhost/v2/userinfo?usercode=463425308`, which returns with a code 0 and correct format.

**Comment by TheSnowfield** [comment]
Did you put arcsong.db into `/savedata/` ?
Best30 function needs rating table to make quering enumeration.

**Comment by iyume** [comment]
```
$ ll savedata/arcsong.db 
-rw-r--r-- 1 iyume iyume 24576 Jan  9 20:47 savedata/arcsong.db
```
It seems the `savedata/arcsong.db` have stored some data, then I try to query some data from it.
```
In [2]: import sqlite3

In [3]: cnx = sqlite3.connect('savedata/arcsong.db')

In [4]: cnx.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall()
Out[4]: [('songs',), ('alias',), ('charts',)]

In [5]: cnx.execute("SELECT * FROM songs;").fetchall()
Out[5]: []

In [6]: cnx.execute("SELECT * FROM alias;").fetchall()
Out[6]: []

In [7]: cnx.execute("SELECT * FROM charts;").fetchall()
Out[7]: []
```
Why `savedata/arcsong.db` is empty? And how can I fix it?

**Comment by TheSnowfield** [comment]
arcsong.db is a sqlite database which stored all of the songs 
information of Arcaea.
It offers song informations, song alias and song rating table. 
Best30 needs song rating table to run correctly.

You could download the latest arcsong.db in [Release Page](.. /../Release) of this repository, And copy it into savedata/ override it.

**Comment by iyume** [comment]
I missed the document carelessly.

After rebuilding, the service can now run normally.

Solved, thx.
